import { jsPDF } from 'jspdf'

export interface AnalysisExportPayload {
  ticker: string
  companyName?: string | null
  verdict?: string | null
  confidence?: number | null
  summary?: string | null
  bullArguments?: string | null
  bearArguments?: string | null
  riskScore?: number | null
  opportunityScore?: number | null
  createdAt?: string | Date | null
}

function escapeCsv(value: string): string {
  return `"${value.replace(/"/g, '""')}"`
}

export function buildAnalysisReportText(payload: AnalysisExportPayload) {
  const lines: string[] = []
  lines.push(`InvestIQ Report - ${payload.companyName ?? payload.ticker}`)
  lines.push(`Ticker: ${payload.ticker}`)
  if (payload.companyName) lines.push(`Company: ${payload.companyName}`)
  if (payload.verdict) lines.push(`Verdict: ${payload.verdict}`)
  if (payload.confidence !== undefined && payload.confidence !== null) lines.push(`Confidence: ${Math.round(payload.confidence * 100)}%`)
  if (payload.riskScore !== undefined && payload.riskScore !== null) lines.push(`Risk Score: ${payload.riskScore}/100`)
  if (payload.opportunityScore !== undefined && payload.opportunityScore !== null) lines.push(`Opportunity Score: ${payload.opportunityScore}/100`)
  if (payload.createdAt) lines.push(`Analyzed: ${new Date(payload.createdAt).toLocaleString()}`)
  lines.push('')
  lines.push('Summary:')
  lines.push(payload.summary ?? 'No summary available.')
  lines.push('')
  lines.push('Bull Case:')
  lines.push((payload.bullArguments ?? 'No bull case available.').split('\n').map((line) => `- ${line}`).join('\n'))
  lines.push('')
  lines.push('Bear Case:')
  lines.push((payload.bearArguments ?? 'No bear case available.').split('\n').map((line) => `- ${line}`).join('\n'))
  lines.push('')
  lines.push('Generated by InvestIQ AI research platform. This report is for informational purposes only.')
  return lines.join('\n')
}

export function buildAnalysisReportCsv(payload: AnalysisExportPayload) {
  const rows: string[][] = [
    ['Field', 'Value'],
    ['Ticker', payload.ticker],
    ['Company', payload.companyName ?? ''],
    ['Verdict', payload.verdict ?? ''],
    ['Confidence', payload.confidence !== undefined && payload.confidence !== null ? `${Math.round(payload.confidence * 100)}%` : ''],
    ['Risk Score', payload.riskScore?.toString() ?? ''],
    ['Opportunity Score', payload.opportunityScore?.toString() ?? ''],
    ['Analyzed', payload.createdAt ? new Date(payload.createdAt).toLocaleString() : ''],
    ['Summary', payload.summary ?? ''],
    ['Bull Case', payload.bullArguments ?? ''],
    ['Bear Case', payload.bearArguments ?? ''],
  ]

  return rows.map((row) => row.map((value) => escapeCsv(value)).join(',')).join('\n')
}

export function buildAnalysisReportJson(payload: AnalysisExportPayload) {
  return JSON.stringify(
    {
      ...payload,
      createdAt: payload.createdAt ? new Date(payload.createdAt).toISOString() : undefined,
    },
    null,
    2
  )
}

export function downloadFile(filename: string, content: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  anchor.click()
  URL.revokeObjectURL(url)
}

export function downloadReportAsText(payload: AnalysisExportPayload) {
  downloadFile(`${payload.ticker}-investiq-report.txt`, buildAnalysisReportText(payload), 'text/plain;charset=utf-8')
}

export function downloadReportAsCsv(payload: AnalysisExportPayload) {
  downloadFile(`${payload.ticker}-investiq-report.csv`, buildAnalysisReportCsv(payload), 'text/csv;charset=utf-8')
}

export function downloadReportAsJson(payload: AnalysisExportPayload) {
  downloadFile(`${payload.ticker}-investiq-report.json`, buildAnalysisReportJson(payload), 'application/json;charset=utf-8')
}

export function buildAnalysisReportPdf(payload: AnalysisExportPayload) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'pt', format: 'a4' })
  const margin = 40
  const lineHeight = 18
  let y = margin

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(18)
  doc.text(`InvestIQ Report - ${payload.companyName ?? payload.ticker}`, margin, y)
  y += lineHeight * 1.5

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(12)

  const addLine = (label: string, value: string) => {
    doc.text(`${label}: ${value}`, margin, y)
    y += lineHeight
  }

  addLine('Ticker', payload.ticker)
  if (payload.companyName) addLine('Company', payload.companyName)
  if (payload.verdict) addLine('Verdict', payload.verdict)
  if (payload.confidence !== undefined && payload.confidence !== null) addLine('Confidence', `${Math.round(payload.confidence * 100)}%`)
  if (payload.riskScore !== undefined && payload.riskScore !== null) addLine('Risk Score', `${payload.riskScore}/100`)
  if (payload.opportunityScore !== undefined && payload.opportunityScore !== null) addLine('Opportunity Score', `${payload.opportunityScore}/100`)
  if (payload.createdAt) addLine('Analyzed', new Date(payload.createdAt).toLocaleString())

  y += lineHeight
  const writeSection = (title: string, content: string) => {
    doc.setFont('helvetica', 'bold')
    doc.text(title, margin, y)
    y += lineHeight
    doc.setFont('helvetica', 'normal')
    const wrapped = doc.splitTextToSize(content, 520)
    doc.text(wrapped, margin, y)
    y += wrapped.length * (lineHeight * 0.9) + lineHeight * 0.4
    if (y > 740) {
      doc.addPage()
      y = margin
    }
  }

  writeSection('Summary', payload.summary ?? 'No summary available.')
  writeSection('Bull Case', payload.bullArguments ?? 'No bull case available.')
  writeSection('Bear Case', payload.bearArguments ?? 'No bear case available.')
  writeSection('Disclaimer', 'Generated by InvestIQ AI research platform. This report is for informational purposes only.')

  return doc
}

export function downloadReportAsPdf(payload: AnalysisExportPayload) {
  const pdf = buildAnalysisReportPdf(payload)
  pdf.save(`${payload.ticker}-investiq-report.pdf`)
}
